### ISSUE TITLE
Build with vendored dependencies fails

### ISSUE THREAD

**Issue by ctarsjp** [webview/webview_go#49]
Trying to build the example as go module with vendored dependencies. Build fails with the following error:

```
> go build
# github.com/webview/webview_go
vendor\github.com\webview\webview_go\webview.go:17:10: fatal error: 'webview.h' file not found
   17 | #include "webview.h"
      |          ^~~~~~~~~~~
1 error generated.
```

OS is Windows 11, but I don't think it's OS-dependent.

Go version is 1.22.5.

Copying `libs` directory to `vendor/github.com/webview/webview_go` solves the issue.

**Comment by ctarsjp** [comment]
I believe that [this](https://github.com/webview/webview_go/issues/14) is the same issue.

**Comment by SteffenL** [comment]
It has been so long since I explored this so I don't quite remember; however, last time I worked on this, this use case was not well supported in Go/cgo. If I recall correctly, I sort of got vendoring to work by adding dummy `*.go` files in the folders that had non-go files.

Can you imagine better solutions?
